version: '3.4'

services:
    postgresdb:
        image: postgres

    elasticsearchs:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2

    redis:
        image: redis

    rabbitmq:
        image: rabbitmq:3-management

    phonebook.api:
        image: ${DOCKER_REGISTRY-}phonebookapi
        build:
            context: .
            dockerfile: src/PhoneBook/PhoneBook.API/Dockerfile

    repositoryservice.api:
        image: ${DOCKER_REGISTRY-}repositoryserviceapi
        build:
            context: .
            dockerfile: src/RepositoryService/RepositoryService.API/Dockerfile

    reportservice.api:
        image: ${DOCKER_REGISTRY-}reportserviceapi
        build:
            context: .
            dockerfile: src/ReportService/ReportService.API/Dockerfile

