// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RepositoryService.Infrastructure.Data;

namespace RepositoryService.Infrastructure.Migrations
{
    [DbContext(typeof(PhonebookContext))]
    [Migration("20211027211021_first-init3")]
    partial class firstinit3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("RepositoryService.Core.Entities.ContactInfo", b =>
                {
                    b.Property<string>("UUID")
                        .HasColumnType("text");

                    b.Property<string>("RecordForeignKey")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UUID");

                    b.HasIndex("RecordForeignKey");

                    b.ToTable("ContactInfos");
                });

            modelBuilder.Entity("RepositoryService.Core.Entities.Record", b =>
                {
                    b.Property<string>("UUID")
                        .HasColumnType("text");

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.HasKey("UUID");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("RepositoryService.Core.Entities.ContactInfo", b =>
                {
                    b.HasOne("RepositoryService.Core.Entities.Record", "Record")
                        .WithMany("ContactInfos")
                        .HasForeignKey("RecordForeignKey");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("RepositoryService.Core.Entities.Record", b =>
                {
                    b.Navigation("ContactInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
